-- ============================================================
-- Lesson Content Seed — auto-generated by generate-lesson-seeds.js
-- Generated: 2026-04-15T20:09:28.900Z
-- ============================================================

-- Delete existing lessons for these courses before re-seeding
DELETE FROM public.lessons WHERE "CourseId" IN (
  SELECT "Id" FROM public.courses WHERE "CourseCode" = 'SE101'
);

-- SE101 lessons
INSERT INTO public.lessons
  ("CourseId", "Title", "Content", "VideoUrl", lesson_type, "OrderIndex", "DurationMinutes", "IsPublished")
SELECT
  c."Id",
  v.title, v.content, v.video_url::text, v.lesson_type, v.order_index, v.duration_minutes, v.is_published
FROM public.courses c
CROSS JOIN (VALUES
  ('Welcome And Overview', '<hr>
<p>title: Welcome to SE101 — Introduction to Programming</p>
<p>type: text</p>
<p>duration: 20</p>
<hr>

<h2>Welcome to SE101</h2>

<p>This course is your entry point into software engineering at ADU. By the end you will write Python programs that solve real problems, understand how computers execute code, and think algorithmically.</p>

<h3>What You Will Learn</h3>

<ul>
<li>Python syntax and core data types</li></ul>

<ul>
<li>Control flow: conditions and loops</li></ul>

<ul>
<li>Functions and modular code</li></ul>

<ul>
<li>Working with files and data</li></ul>

<ul>
<li>Algorithmic thinking and problem decomposition</li></ul>


<h3>Tools You Need</h3>

<p>Install Python 3.11+ from <strong>python.org</strong> and VS Code with the Python extension.</p>

<p>``<code>bash</p>
<p>python --version   # should print Python 3.11+</p>
<p>pip --version      # package manager</p>
<p></code>``</p>

<h3>How This Course Works</h3>

<p>Each lesson builds on the previous one. Complete the exercises at the end of each lesson before moving on. The final lesson is a mini-project that ties everything together.</p>', NULL, 'text', 1, 30, true),
  ('Variables And Data Types', '<hr>
<p>title: Variables, Data Types & Operators</p>
<p>type: code</p>
<p>duration: 45</p>
<hr>

<h2>Variables and Data Types</h2>

<p>A variable is a named container for a value. Python is dynamically typed — you do not declare types explicitly.</p>

<p>``<code>python</p>
<h1>Integers</h1>
<p>age = 21</p>
<p>year = 2026</p>

<h1>Floats</h1>
<p>gpa = 3.75</p>

<h1>Strings</h1>
<p>name = "Amara Diallo"</p>

<h1>Booleans</h1>
<p>is_enrolled = True</p>

<h1>Check the type</h1>
<p>print(type(age))    # <class ''int''></p>
<p>print(type(name))   # <class ''str''></p>
<p></code>`<code></p>

<h3>Arithmetic Operators</h3>

<p></code>`<code>python</p>
<p>x = 10</p>
<p>y = 3</p>

<p>print(x + y)   # 13  — addition</p>
<p>print(x - y)   # 7   — subtraction</p>
<p>print(x * y)   # 30  — multiplication</p>
<p>print(x / y)   # 3.333 — true division</p>
<p>print(x // y)  # 3   — floor division</p>
<p>print(x % y)   # 1   — modulo (remainder)</p>
<p>print(x ** y)  # 1000 — exponentiation</p>
<p></code>`<code></p>

<h3>String Operations</h3>

<p></code>`<code>python</p>
<p>first = "Kwame"</p>
<p>last  = "Mensah"</p>
<p>full  = first + " " + last       # concatenation</p>
<p>greeting = f"Hello, {full}!"     # f-string (preferred)</p>
<p>print(greeting.upper())          # HELLO, KWAME MENSAH!</p>
<p>print(len(full))                 # 11</p>
<p></code>``</p>', NULL, 'text', 2, 30, true)
) AS v(title, content, video_url, lesson_type, order_index, duration_minutes, is_published)
WHERE c."CourseCode" = 'SE101';

-- Summary: 2 lessons across 1 courses